version: '2'
services:
  mysql-master:
    image: mysql
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "mysql-local"
      MYSQL_PASSWORD: "mysql-local"
      MYSQL_DATABASE: "mysql-local"
      LANG: C.UTF-8
      TZ: Asia/Seoul
    ports:
      - 3306:3306
  mysql-slave:
    image: mysql
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "mysql-local-slave"
      MYSQL_PASSWORD: "mysql-local-slave"
      MYSQL_DATABASE: "mysql-local-slave"
      LANG: C.UTF-8
      TZ: Asia/Seoul
    ports:
      - 13306:3306
  redis:
    image: redis
    container_name: redis-local
    ports:
      - 6379:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch-local
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-local
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-local
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181
      KAFKA_CREATE_TOPICS: "topic1:4:1,topic2:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: mongo
    container_name: "mongo-local"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="mongo-local"
      - MONGODB_PASS="mongo-local"
    ports:
      - 27017:27017