version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch-local
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300