version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "mysql-local"
      MYSQL_PASSWORD: "mysql-local"
      MYSQL_DATABASE: "mysql-local"
    ports:
      - 3306:3306